shardbox/catalog

catalog/Algorithms_and_Data_structures.yml, catalog/C_bindings.yml, catalog/Compression.yml, catalog/Data_Formats.yml, catalog/HTTP.yml, catalog/Network_Protocols.yml, shard.lock
veelenga/awesome_list ebf3a93e
=> Import awesome_list

catalog/Validation.yml
=> Add nicolab/validator

catalog/Cryptography.yml
GitHub: marcobellaccini/nanvault - encrypt and decrypt files in the Ansible Vault format
=> Added nanvault to Cryptography.yml

catalog/Logging_and_monitoring.yml
Add a new shard 'syslogger': https://www.github.com/lazau/syslogger
=> Add github.com/lazau/syslogger shard info

catalog/Algorithms_and_Data_structures.yml
https://github.com/Sija/blurhash.cr
=> Add blurhash.cr

catalog/Audio.yml, catalog/Misc.yml
=> Adding libao audio bindings & Term colors shard

catalog/Algorithms_and_Data_structures.yml
=> Add benfordslaw.cr & chi-squared shards

catalog/Framework_Components.yml
=> Add `GrottoPress/shield`

catalog/Third-party_APIs.yml
Adds binance project to the 3rd party APIs catalog
=> add binance to 3rd party apis 

catalog/C_bindings.yml
=> add ettomatic/xattr

catalog/Image_processing.yml
=> Added jetrockets/fastimage.cr

catalog/Blockchain.yml, catalog/CLI_Utils.yml, catalog/Code_Analysis_and_Metrics.yml, catalog/Configuration.yml, catalog/Data_Formats.yml, catalog/Database_Drivers_Clients.yml, catalog/Environment_Management.yml, catalog/Framework_Components.yml, catalog/GUI_Development.yml, catalog/Game_Development.yml, catalog/HTML_XML_Parsing.yml, catalog/HTTP.yml, catalog/Image_processing.yml, catalog/Misc.yml, catalog/Network_Protocols.yml, catalog/Science_and_Data_analysis.yml, catalog/Serverless_Computing.yml, catalog/Task_management.yml, catalog/Third-party_APIs.yml, catalog/Validation.yml, catalog/Web_Frameworks.yml
=> Add shards from awesomelist

catalog/Third-party_APIs.yml
Caridina is a [Matrix](http://matrix.org) client I am developing and using in some projects.
=> Add Caridina

catalog/Scheduling.yml
Hi,
This is a new library by myself that I use in some project. It should be stable enough for little projects.
Thanks.
=> Add marmot

catalog/Algorithms_and_Data_structures.yml, catalog/Implementations_Compilers.yml, catalog/Parser_Generators.yml
* Moved dhruvrajvanshi/crystal-parsec, jemc/crystal-pegmatite, and DanilaFe/pegasus into
"Parser Generators".
=> Added a new category "Parser Generators".

catalog/CLI_Applications.yml
Another project of mine: https://github.com/erdnaxeli/castblock
=> Add Castblock

catalog/Third-party_APIs.yml
=> Add srcr shard

catalog/Web_Applications.yml
Invidious repo has moved to iv-org/invidious
=> Update Invidious location

catalog/Natural_Language.yml
The Crystal ecosystem has been getting quite a lot of new i18n shards recently. It may be worthwhile to add a new dedicated section for it.
=> Add Lens - a multiformat internationalization shard

catalog/Algorithms_and_Data_structures.yml, catalog/Third-party_APIs.yml
sorry about the whitespace diff. vscode formatted it >.<
=> Add new K8S libs

catalog/C_bindings.yml, catalog/Cryptography.yml, catalog/Framework_Components.yml, catalog/Game_Development.yml, catalog/HTML_XML_Parsing.yml, catalog/Internationalization.yml, catalog/Natural_Language.yml
29a36ebae74fcb346f3b847d5302b8dbc7d00de7
=> Update shards from awesomelist

catalog/GUI_library.yml, catalog/Game_Development.yml, catalog/Network_Protocols.yml
These are actually a bit out of date, but I figured I'd put them in the catalog so it's easier for someone to potentially find them and continue development.
=> Added a few GUI shards

catalog/Web_Frameworks.yml
This pull request adds the [Marten web framework](https://github.com/martenframework/marten) to the web framework catalog.
=> Add Marten web framework

catalog/CLI_Builders.yml
Added my new shard [arg_parser](https://github.com/watzon/arg_parser)
=> Add arg_parser

catalog/Logging_and_monitoring.yml
This PR adds `todo_or_diehard` under logging/monitoring.
=> Add todo_or_diehard

catalog/CLI_Builders.yml
Adds [Cling](https://github.com/devnote-dev/cling) v3!
=> feat: add cling

catalog/HTML_Builders.yml
Add [blueprint](https://github.com/gunbolt/blueprint) to HTML builders.
=> Add blueprint to HTML_Builders.yml

catalog/CLI_Applications.yml, catalog/Networking.yml
=> add miniss

catalog/C_bindings.yml
=> add urlencoding shard

catalog/Game_Development.yml
Hi, current author of raylib-cr here, please change, the original is archived. The old one is not a valid mirror and does not work on current Crystal versions.
=> Change raylib-cr to current author

catalog/Data_Formats.yml
https://github.com/d1ceward/xlsx-parser
=> Add xlsx-parser

catalog/Data_Formats.yml
=> add syeopite/ctoml-cr

catalog/Web_Frameworks.yml
=> Revert "Temporarily remove athena legacy repo"

catalog/Natural_Language.yml
=> Added whichlang cr

BLACKLIST, catalog/CLI_Utils.yml, catalog/C_bindings.yml, catalog/Caching.yml, catalog/Data_Formats.yml, catalog/Database_Tools.yml, catalog/Framework_Components.yml, catalog/GUI_Development.yml, catalog/HTML_XML_Parsing.yml, catalog/Internationalization.yml, catalog/Misc.yml, catalog/Processes_and_Threads.yml, catalog/Queues_and_Messaging.yml, catalog/Science_and_Data_analysis.yml, catalog/Testing.yml, catalog/Web_Frameworks.yml
Sorted first ten uncategorized shards; added amber-crystal/quartz-mailer to blacklist as it is a duplicate for amberframework/quartz-mailer
=> Add uncategorized shards to the catalog

catalog/Third-party_APIs.yml
API Client interface for https://openrouter.ai
=> added petterthowsen/openrouter: Client for openrouter.ai

catalog/C_bindings.yml, catalog/GUI_library.yml
=> Add ior and wayland_client to catalog

catalog/Data_Formats.yml
#
#
Might as well add this old thing I have lying around.
=> Add hdrhistogram
